// Copyright (c) 2012, Fuji Xerox Co., Ltd.
// All rights reserved.
// Author: Surendar Chandra, FX Palo Alto Laboratory, Inc.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Net;
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace aaa 
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AaaBinding", Namespace="http://cisco.com/mse")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesObject))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(containEl[]))]
public partial class aaaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback LoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback LogoutOperationCompleted;
    
    /// <remarks/>
    public aaaService() {
        this.Url = "https://192.168.20.84:8008/aaa/";
    }
    
        /// <remarks/>
    public aaaService(string url)
        {
            this.Url = url;
        }
    protected override WebRequest GetWebRequest(Uri uri)
    {
            
      HttpWebRequest webRequest = (HttpWebRequest)base.GetWebRequest(uri);
      webRequest.KeepAlive = false;
      webRequest.ProtocolVersion = HttpVersion.Version10; // 
      ServicePointManager.ServerCertificateValidationCallback += new System.Net.Security.RemoteCertificateValidationCallback(ValidateServerCertificate);
      return webRequest;

    }

   public static bool ValidateServerCertificate(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors)
   {
     return true;
   }
/*    protected override WebRequest GetWebRequest(Uri uri)
    {
        //Microsoft.Web.Services2.SoapWebRequest webRequest = (Microsoft.Web.Services2.SoapWebRequest)base.GetWebRequest(uri);

        HttpWebRequest webRequest = (HttpWebRequest)base.GetWebRequest(uri);
        webRequest.KeepAlive = false;
        webRequest.ProtocolVersion = HttpVersion.Version10; // 
        return webRequest;
    }*/

    /// <remarks/>
    public event LoginCompletedEventHandler LoginCompleted;
    
    /// <remarks/>
    public event LogoutCompletedEventHandler LogoutCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Login", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Session", Namespace="http://cisco.com/mse/types")]
    public Session Login([System.Xml.Serialization.XmlElementAttribute("Login", Namespace="http://cisco.com/mse/types")] LoginMethodArgs Login1) {
        object[] results = this.Invoke("Login", new object[] {
                    Login1});
        return ((Session)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLogin(LoginMethodArgs Login1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Login", new object[] {
                    Login1}, callback, asyncState);
    }
    
    /// <remarks/>
    public Session EndLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Session)(results[0]));
    }
    
    /// <remarks/>
    public void LoginAsync(LoginMethodArgs Login1) {
        this.LoginAsync(Login1, null);
    }
    
    /// <remarks/>
    public void LoginAsync(LoginMethodArgs Login1, object userState) {
        if ((this.LoginOperationCompleted == null)) {
            this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
        }
        this.InvokeAsync("Login", new object[] {
                    Login1}, this.LoginOperationCompleted, userState);
    }
    
    private void OnLoginOperationCompleted(object arg) {
        if ((this.LoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Logout", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://cisco.com/mse/types")]
    public Response Logout([System.Xml.Serialization.XmlElementAttribute("Logout", Namespace="http://cisco.com/mse/types")] LogoutMethodArgs Logout1) {
        object[] results = this.Invoke("Logout", new object[] {
                    Logout1});
        return ((Response)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLogout(LogoutMethodArgs Logout1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Logout", new object[] {
                    Logout1}, callback, asyncState);
    }
    
    /// <remarks/>
    public Response EndLogout(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Response)(results[0]));
    }
    
    /// <remarks/>
    public void LogoutAsync(LogoutMethodArgs Logout1) {
        this.LogoutAsync(Logout1, null);
    }
    
    /// <remarks/>
    public void LogoutAsync(LogoutMethodArgs Logout1, object userState) {
        if ((this.LogoutOperationCompleted == null)) {
            this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
        }
        this.InvokeAsync("Logout", new object[] {
                    Logout1}, this.LogoutOperationCompleted, userState);
    }
    
    private void OnLogoutOperationCompleted(object arg) {
        if ((this.LogoutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class LoginMethodArgs : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AesLogin aesLoginField;
    
    /// <remarks/>
    public AesLogin AesLogin {
        get {
            return this.aesLoginField;
        }
        set {
            this.aesLoginField = value;
            this.RaisePropertyChanged("AesLogin");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesLogin : AesObject {
    
    private string userNameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
            this.RaisePropertyChanged("userName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
            this.RaisePropertyChanged("password");
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesLogout))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesLogin))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesHistoryQueryArgs))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hierEl))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(containEl))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesQueryCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesSortCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesMacAddressCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesAreaCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesTelemetryCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesObjOp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesBusinessSession))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesObject : object, System.ComponentModel.INotifyPropertyChanged {
    
    private long objectIdField;
    
    private bool objectIdFieldSpecified;
    
    private long parentIdField;
    
    private bool parentIdFieldSpecified;
    
    private long changedOnField;
    
    private bool changedOnFieldSpecified;
    
    private int maskField;
    
    private bool maskFieldSpecified;
    
    private int optionsField;
    
    private bool optionsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long objectId {
        get {
            return this.objectIdField;
        }
        set {
            this.objectIdField = value;
            this.RaisePropertyChanged("objectId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool objectIdSpecified {
        get {
            return this.objectIdFieldSpecified;
        }
        set {
            this.objectIdFieldSpecified = value;
            this.RaisePropertyChanged("objectIdSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long parentId {
        get {
            return this.parentIdField;
        }
        set {
            this.parentIdField = value;
            this.RaisePropertyChanged("parentId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool parentIdSpecified {
        get {
            return this.parentIdFieldSpecified;
        }
        set {
            this.parentIdFieldSpecified = value;
            this.RaisePropertyChanged("parentIdSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long changedOn {
        get {
            return this.changedOnField;
        }
        set {
            this.changedOnField = value;
            this.RaisePropertyChanged("changedOn");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool changedOnSpecified {
        get {
            return this.changedOnFieldSpecified;
        }
        set {
            this.changedOnFieldSpecified = value;
            this.RaisePropertyChanged("changedOnSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
            this.RaisePropertyChanged("mask");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maskSpecified {
        get {
            return this.maskFieldSpecified;
        }
        set {
            this.maskFieldSpecified = value;
            this.RaisePropertyChanged("maskSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
            this.RaisePropertyChanged("options");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionsSpecified {
        get {
            return this.optionsFieldSpecified;
        }
        set {
            this.optionsFieldSpecified = value;
            this.RaisePropertyChanged("optionsSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AesObject itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AesBusinessSession", typeof(AesBusinessSession))]
    [System.Xml.Serialization.XmlElementAttribute("AesResult", typeof(AesResult))]
    public AesObject Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
            this.RaisePropertyChanged("Item");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesBusinessSession : AesObject {
    
    private int idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("id");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesResult : AesObject {
    
    private bool resultField;
    
    private bool resultFieldSpecified;
    
    private string resultArgField;
    
    private string resultArgClassField;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
            this.RaisePropertyChanged("result");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultSpecified {
        get {
            return this.resultFieldSpecified;
        }
        set {
            this.resultFieldSpecified = value;
            this.RaisePropertyChanged("resultSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resultArg {
        get {
            return this.resultArgField;
        }
        set {
            this.resultArgField = value;
            this.RaisePropertyChanged("resultArg");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resultArgClass {
        get {
            return this.resultArgClassField;
        }
        set {
            this.resultArgClassField = value;
            this.RaisePropertyChanged("resultArgClass");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
            this.RaisePropertyChanged("message");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class LogoutMethodArgs : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AesBusinessSession aesBusinessSessionField;
    
    private AesLogout aesLogoutField;
    
    /// <remarks/>
    public AesBusinessSession AesBusinessSession {
        get {
            return this.aesBusinessSessionField;
        }
        set {
            this.aesBusinessSessionField = value;
            this.RaisePropertyChanged("AesBusinessSession");
        }
    }
    
    /// <remarks/>
    public AesLogout AesLogout {
        get {
            return this.aesLogoutField;
        }
        set {
            this.aesLogoutField = value;
            this.RaisePropertyChanged("AesLogout");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesLogout : AesObject {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class Session : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AesBusinessSession aesBusinessSessionField;
    
    /// <remarks/>
    public AesBusinessSession AesBusinessSession {
        get {
            return this.aesBusinessSessionField;
        }
        set {
            this.aesBusinessSessionField = value;
            this.RaisePropertyChanged("AesBusinessSession");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesMatchMbrCriteria : object, System.ComponentModel.INotifyPropertyChanged {
    
    private int operatorField;
    
    private bool operatorFieldSpecified;
    
    private string matchClassField;
    
    private string matchMbrField;
    
    private string matchValueField;
    
    private string valueClassField;
    
    private string matchListField;
    
    private string matchSizeField;
    
    private string matchElemField;
    
    private string caseInsensitiveField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int @operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
            this.RaisePropertyChanged("operator");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool operatorSpecified {
        get {
            return this.operatorFieldSpecified;
        }
        set {
            this.operatorFieldSpecified = value;
            this.RaisePropertyChanged("operatorSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchClass {
        get {
            return this.matchClassField;
        }
        set {
            this.matchClassField = value;
            this.RaisePropertyChanged("matchClass");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchMbr {
        get {
            return this.matchMbrField;
        }
        set {
            this.matchMbrField = value;
            this.RaisePropertyChanged("matchMbr");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchValue {
        get {
            return this.matchValueField;
        }
        set {
            this.matchValueField = value;
            this.RaisePropertyChanged("matchValue");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueClass {
        get {
            return this.valueClassField;
        }
        set {
            this.valueClassField = value;
            this.RaisePropertyChanged("valueClass");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchList {
        get {
            return this.matchListField;
        }
        set {
            this.matchListField = value;
            this.RaisePropertyChanged("matchList");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchSize {
        get {
            return this.matchSizeField;
        }
        set {
            this.matchSizeField = value;
            this.RaisePropertyChanged("matchSize");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string matchElem {
        get {
            return this.matchElemField;
        }
        set {
            this.matchElemField = value;
            this.RaisePropertyChanged("matchElem");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string caseInsensitive {
        get {
            return this.caseInsensitiveField;
        }
        set {
            this.caseInsensitiveField = value;
            this.RaisePropertyChanged("caseInsensitive");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class containEl : AesObject {
    
    private hierEl[] hierElField;
    
    private string containClField;
    
    private int sizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hierEl")]
    public hierEl[] hierEl {
        get {
            return this.hierElField;
        }
        set {
            this.hierElField = value;
            this.RaisePropertyChanged("hierEl");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string containCl {
        get {
            return this.containClField;
        }
        set {
            this.containClField = value;
            this.RaisePropertyChanged("containCl");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
            this.RaisePropertyChanged("size");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class hierEl : AesObject {
    
    private string valField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
            this.RaisePropertyChanged("val");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesHistoryQueryArgs : AesObject {
    
    private int startIndexField;
    
    private string numOfResultsField;
    
    private bool isCountQueryField;
    
    private long fromTimeMillisField;
    
    private bool fromTimeMillisFieldSpecified;
    
    private long toTimeMillisField;
    
    private bool toTimeMillisFieldSpecified;
    
    private long floorIdField;
    
    private bool floorIdFieldSpecified;
    
    private string macAddressField;
    
    public AesHistoryQueryArgs() {
        this.startIndexField = 0;
        this.isCountQueryField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int startIndex {
        get {
            return this.startIndexField;
        }
        set {
            this.startIndexField = value;
            this.RaisePropertyChanged("startIndex");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string numOfResults {
        get {
            return this.numOfResultsField;
        }
        set {
            this.numOfResultsField = value;
            this.RaisePropertyChanged("numOfResults");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isCountQuery {
        get {
            return this.isCountQueryField;
        }
        set {
            this.isCountQueryField = value;
            this.RaisePropertyChanged("isCountQuery");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long fromTimeMillis {
        get {
            return this.fromTimeMillisField;
        }
        set {
            this.fromTimeMillisField = value;
            this.RaisePropertyChanged("fromTimeMillis");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fromTimeMillisSpecified {
        get {
            return this.fromTimeMillisFieldSpecified;
        }
        set {
            this.fromTimeMillisFieldSpecified = value;
            this.RaisePropertyChanged("fromTimeMillisSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long toTimeMillis {
        get {
            return this.toTimeMillisField;
        }
        set {
            this.toTimeMillisField = value;
            this.RaisePropertyChanged("toTimeMillis");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool toTimeMillisSpecified {
        get {
            return this.toTimeMillisFieldSpecified;
        }
        set {
            this.toTimeMillisFieldSpecified = value;
            this.RaisePropertyChanged("toTimeMillisSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long floorId {
        get {
            return this.floorIdField;
        }
        set {
            this.floorIdField = value;
            this.RaisePropertyChanged("floorId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool floorIdSpecified {
        get {
            return this.floorIdFieldSpecified;
        }
        set {
            this.floorIdFieldSpecified = value;
            this.RaisePropertyChanged("floorIdSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string macAddress {
        get {
            return this.macAddressField;
        }
        set {
            this.macAddressField = value;
            this.RaisePropertyChanged("macAddress");
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesQueryCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesSortCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesMacAddressCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesAreaCriteria))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AesTelemetryCriteria))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesCriteria : AesObject {
    
    private AesCriteriaAndlist andlistField;
    
    private AesCriteriaOrlist orlistField;
    
    private bool subCriteriaField;
    
    private bool subCriteriaFieldSpecified;
    
    private bool andTermField;
    
    private bool andTermFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("and-list")]
    public AesCriteriaAndlist andlist {
        get {
            return this.andlistField;
        }
        set {
            this.andlistField = value;
            this.RaisePropertyChanged("andlist");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("or-list")]
    public AesCriteriaOrlist orlist {
        get {
            return this.orlistField;
        }
        set {
            this.orlistField = value;
            this.RaisePropertyChanged("orlist");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool subCriteria {
        get {
            return this.subCriteriaField;
        }
        set {
            this.subCriteriaField = value;
            this.RaisePropertyChanged("subCriteria");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool subCriteriaSpecified {
        get {
            return this.subCriteriaFieldSpecified;
        }
        set {
            this.subCriteriaFieldSpecified = value;
            this.RaisePropertyChanged("subCriteriaSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool andTerm {
        get {
            return this.andTermField;
        }
        set {
            this.andTermField = value;
            this.RaisePropertyChanged("andTerm");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool andTermSpecified {
        get {
            return this.andTermFieldSpecified;
        }
        set {
            this.andTermFieldSpecified = value;
            this.RaisePropertyChanged("andTermSpecified");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cisco.com/mse/types")]
public partial class AesCriteriaAndlist : object, System.ComponentModel.INotifyPropertyChanged {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AesAreaCriteria", typeof(AesAreaCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesMacAddressCriteria", typeof(AesMacAddressCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesMatchMbrCriteria", typeof(AesMatchMbrCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesTelemetryCriteria", typeof(AesTelemetryCriteria))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
            this.RaisePropertyChanged("Items");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesAreaCriteria : AesCriteria {
    
    private string outsideField;
    
    private string areaRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outside {
        get {
            return this.outsideField;
        }
        set {
            this.outsideField = value;
            this.RaisePropertyChanged("outside");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string areaRef {
        get {
            return this.areaRefField;
        }
        set {
            this.areaRefField = value;
            this.RaisePropertyChanged("areaRef");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesMacAddressCriteria : AesCriteria {
    
    private string macAddressField;
    
    private string addressMaskField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string macAddress {
        get {
            return this.macAddressField;
        }
        set {
            this.macAddressField = value;
            this.RaisePropertyChanged("macAddress");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string addressMask {
        get {
            return this.addressMaskField;
        }
        set {
            this.addressMaskField = value;
            this.RaisePropertyChanged("addressMask");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesTelemetryCriteria : AesCriteria {
    
    private bool caseInsensitiveField;
    
    private bool caseInsensitiveFieldSpecified;
    
    private string operatorField;
    
    private string telemFieldField;
    
    private string telemValueField;
    
    private string valueClassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool caseInsensitive {
        get {
            return this.caseInsensitiveField;
        }
        set {
            this.caseInsensitiveField = value;
            this.RaisePropertyChanged("caseInsensitive");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool caseInsensitiveSpecified {
        get {
            return this.caseInsensitiveFieldSpecified;
        }
        set {
            this.caseInsensitiveFieldSpecified = value;
            this.RaisePropertyChanged("caseInsensitiveSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
            this.RaisePropertyChanged("operator");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telemField {
        get {
            return this.telemFieldField;
        }
        set {
            this.telemFieldField = value;
            this.RaisePropertyChanged("telemField");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telemValue {
        get {
            return this.telemValueField;
        }
        set {
            this.telemValueField = value;
            this.RaisePropertyChanged("telemValue");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueClass {
        get {
            return this.valueClassField;
        }
        set {
            this.valueClassField = value;
            this.RaisePropertyChanged("valueClass");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cisco.com/mse/types")]
public partial class AesCriteriaOrlist : object, System.ComponentModel.INotifyPropertyChanged {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AesAreaCriteria", typeof(AesAreaCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesMacAddressCriteria", typeof(AesMacAddressCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesMatchMbrCriteria", typeof(AesMatchMbrCriteria))]
    [System.Xml.Serialization.XmlElementAttribute("AesTelemetryCriteria", typeof(AesTelemetryCriteria))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
            this.RaisePropertyChanged("Items");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesQueryCriteria : AesCriteria {
    
    private AesQueryCriteriaSortCriteria sortCriteriaField;
    
    private containEl[] containListField;
    
    private int startIndexField;
    
    private int numOfResultsField;
    
    private bool numOfResultsFieldSpecified;
    
    private bool isCountQueryField;
    
    private int containList1Field;
    
    private int sizeField;
    
    private bool sizeFieldSpecified;
    
    private string containClField;
    
    private string containElField;
    
    private string hierElField;
    
    private string valField;
    
    public AesQueryCriteria() {
        this.startIndexField = 0;
        this.isCountQueryField = false;
        this.containList1Field = 0;
    }
    
    /// <remarks/>
    public AesQueryCriteriaSortCriteria sortCriteria {
        get {
            return this.sortCriteriaField;
        }
        set {
            this.sortCriteriaField = value;
            this.RaisePropertyChanged("sortCriteria");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public containEl[] containList {
        get {
            return this.containListField;
        }
        set {
            this.containListField = value;
            this.RaisePropertyChanged("containList");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int startIndex {
        get {
            return this.startIndexField;
        }
        set {
            this.startIndexField = value;
            this.RaisePropertyChanged("startIndex");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numOfResults {
        get {
            return this.numOfResultsField;
        }
        set {
            this.numOfResultsField = value;
            this.RaisePropertyChanged("numOfResults");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numOfResultsSpecified {
        get {
            return this.numOfResultsFieldSpecified;
        }
        set {
            this.numOfResultsFieldSpecified = value;
            this.RaisePropertyChanged("numOfResultsSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isCountQuery {
        get {
            return this.isCountQueryField;
        }
        set {
            this.isCountQueryField = value;
            this.RaisePropertyChanged("isCountQuery");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("containList")]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int containList1 {
        get {
            return this.containList1Field;
        }
        set {
            this.containList1Field = value;
            this.RaisePropertyChanged("containList1");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
            this.RaisePropertyChanged("size");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeSpecified {
        get {
            return this.sizeFieldSpecified;
        }
        set {
            this.sizeFieldSpecified = value;
            this.RaisePropertyChanged("sizeSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string containCl {
        get {
            return this.containClField;
        }
        set {
            this.containClField = value;
            this.RaisePropertyChanged("containCl");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string containEl {
        get {
            return this.containElField;
        }
        set {
            this.containElField = value;
            this.RaisePropertyChanged("containEl");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hierEl {
        get {
            return this.hierElField;
        }
        set {
            this.hierElField = value;
            this.RaisePropertyChanged("hierEl");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
            this.RaisePropertyChanged("val");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cisco.com/mse/types")]
public partial class AesQueryCriteriaSortCriteria : object, System.ComponentModel.INotifyPropertyChanged {
    
    private AesSortCriteria aesSortCriteriaField;
    
    /// <remarks/>
    public AesSortCriteria AesSortCriteria {
        get {
            return this.aesSortCriteriaField;
        }
        set {
            this.aesSortCriteriaField = value;
            this.RaisePropertyChanged("AesSortCriteria");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesSortCriteria : AesCriteria {
    
    private string sortColumnsField;
    
    private bool isDescendingField;
    
    private string macAddressField;
    
    private string idField;
    
    private string floorField;
    
    private string nameField;
    
    private string groupField;
    
    private string columnField;
    
    public AesSortCriteria() {
        this.isDescendingField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sortColumns {
        get {
            return this.sortColumnsField;
        }
        set {
            this.sortColumnsField = value;
            this.RaisePropertyChanged("sortColumns");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isDescending {
        get {
            return this.isDescendingField;
        }
        set {
            this.isDescendingField = value;
            this.RaisePropertyChanged("isDescending");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string macAddress {
        get {
            return this.macAddressField;
        }
        set {
            this.macAddressField = value;
            this.RaisePropertyChanged("macAddress");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("id");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string floor {
        get {
            return this.floorField;
        }
        set {
            this.floorField = value;
            this.RaisePropertyChanged("floor");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
            this.RaisePropertyChanged("group");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
            this.RaisePropertyChanged("column");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cisco.com/mse/types")]
public partial class AesObjOp : AesObject {
    
    private string objClassNameField;
    
    private string objExternalKeyField;
    
    private long objObjectIdField;
    
    private bool objObjectIdFieldSpecified;
    
    private int opTypeField;
    
    private bool opTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objClassName {
        get {
            return this.objClassNameField;
        }
        set {
            this.objClassNameField = value;
            this.RaisePropertyChanged("objClassName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objExternalKey {
        get {
            return this.objExternalKeyField;
        }
        set {
            this.objExternalKeyField = value;
            this.RaisePropertyChanged("objExternalKey");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long objObjectId {
        get {
            return this.objObjectIdField;
        }
        set {
            this.objObjectIdField = value;
            this.RaisePropertyChanged("objObjectId");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool objObjectIdSpecified {
        get {
            return this.objObjectIdFieldSpecified;
        }
        set {
            this.objObjectIdFieldSpecified = value;
            this.RaisePropertyChanged("objObjectIdSpecified");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int opType {
        get {
            return this.opTypeField;
        }
        set {
            this.opTypeField = value;
            this.RaisePropertyChanged("opType");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool opTypeSpecified {
        get {
            return this.opTypeFieldSpecified;
        }
        set {
            this.opTypeFieldSpecified = value;
            this.RaisePropertyChanged("opTypeSpecified");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Session Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Session)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Response Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Response)(this.results[0]));
        }
    }
}
}